repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910-1"
    hooks:
      - id: mypy
        additional_dependencies:
          [types-Jinja2, types-requests, openpyxl-stubs, types-python-dateutil]
        exclude: docs/
